version: '3'

services:
  gateway: 
    container_name: scans-gateway
    build: 
      context: .
    image: "scans-gateway:latest"
    ports:
      - 4000:4000
    environment:
      REGISTER_SVC_URL: "0.0.0.0:5051"